### ISSUE TITLE
不显示「分类」栏

### ISSUE THREAD

**Issue by jacklanda** [iMuFeng/bmdb#12]
如题，其它的部分都正常工作，但就是页面不显示「分类」栏，我需要怎么进行配置呢？
两个js和样式都按照说明引用了，但就是没有category这一元素。
![图片](https://user-images.githubusercontent.com/54089835/98457648-682cb880-21c4-11eb-9469-1d2107887770.png)

**Comment by iMuFeng** [comment]
能提供更加详细的信息么，比如版本号，博客地址

**Comment by jacklanda** [comment]
> 能提供更加详细的信息么，比如版本号，博客地址

这是页面地址：blog.jacklanda.me/zh/movie
我的配置如下：
![图片](https://user-images.githubusercontent.com/54089835/98666330-d5d51200-2387-11eb-9308-2aa06d2451c1.png)
![图片](https://user-images.githubusercontent.com/54089835/98665798-1a13e280-2387-11eb-9411-9201d7856cdc.png)

猜测可能是引用的cdn资源版本太旧了？

**Comment by iMuFeng** [comment]
老版本默认[不显示分类](https://github.com/iMuFeng/bmdb/tree/1.8.0#3-初始化参数)，需要在配置里面加入：

```
showCategories: true
```

**Comment by jacklanda** [comment]
> 老版本默认[不显示分类](https://github.com/iMuFeng/bmdb/tree/1.8.0#3-%E5%88%9D%E5%A7%8B%E5%8C%96%E5%8F%82%E6%95%B0)，需要在配置里面加入：
> 
> ```
> showCategories: true
> ```

谢谢，照您说的做，我的问题得到了解决。不过，我应该如何使用最新版本呢？您在README里只提到了引入最新版本的js文件，没有提到对应的css从哪引入。

**Comment by iMuFeng** [comment]
> > 老版本默认[不显示分类](https://github.com/iMuFeng/bmdb/tree/1.8.0#3-%E5%88%9D%E5%A7%8B%E5%8C%96%E5%8F%82%E6%95%B0)，需要在配置里面加入：
> > ```
> > showCategories: true
> > ```
> 
> 谢谢，照您说的做，我的问题得到了解决。不过，我应该如何使用最新版本呢？您在README里只提到了引入最新版本的js文件，没有提到对应的css从哪引入。

最新版本不需要额外引入 css

**Comment by jacklanda** [comment]
> > > 老版本默认[不显示分类](https://github.com/iMuFeng/bmdb/tree/1.8.0#3-%E5%88%9D%E5%A7%8B%E5%8C%96%E5%8F%82%E6%95%B0)，需要在配置里面加入：
> > > ```
> > > showCategories: true
> > > ```
> > 
> > 
> > 谢谢，照您说的做，我的问题得到了解决。不过，我应该如何使用最新版本呢？您在README里只提到了引入最新版本的js文件，没有提到对应的css从哪引入。
> 
> 最新版本不需要额外引入 css

好的，已解决问题，谢谢～
