### ISSUE TITLE
现在书籍页面不显示了

### ISSUE THREAD

**Issue by rguo97** [iMuFeng/bmdb#13]
可以看到有正确的请求返回，但是没办法同步，或者说显示不到正确的页面

**Comment by lhymwm** [comment]
我也更新了版本，更新为3.1.0后，书籍和电影都不显示了，博客：https://lhymwm.github.io/guanying/

**Comment by lhymwm** [comment]
> 能提供更加详细的信息么，比如版本号，博客地址

您的博客页面的电影也看不见了，https://mufeng.me/movie#starred

**Comment by iMuFeng** [comment]
> > 能提供更加详细的信息么，比如版本号，博客地址
> 
> 您的博客页面的电影也看不见了，https://mufeng.me/movie#starred

服务器忘了续期 🐶

**Comment by yyl125** [comment]
> > > 能提供更加详细的信息么，比如版本号，博客地址
> > 
> > 
> > 您的博客页面的电影也看不见了，https://mufeng.me/movie#starred
> 
> 服务器忘了续期 🐶

这两天请求时提示超时，发现布克牧为官网也无法打开了，是服务器的问题吗？
